name: PiratedGame Auto Update

on:
  schedule:
    - cron: '0 0 * * *' # Täglich um Mitternacht
  workflow_dispatch: # Manueller Start möglich

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Scraper
        run: python pirated_scraper.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add games-data.json
          git commit -m "Auto-update games from piratedgame.com" || exit 0
          git push
